gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: "true"
      hajimari.io/icon: "source-repository"
      nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/gitea/dark.css"></head>';
            sub_filter_once on;
    hosts:
      - host: &host git.dex136.xyz
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.dex136.xyz
      webhook:
        ALLOWED_HOST_LIST: '*'
  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
