---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-statuspage
spec:
  serviceAccountName: terraform-sa
  triggers:
    - name: gitea-statuspage
      bindings:
        - ref: tb-gitea-statuspage
      template:
        spec:
          params:
            - name: gitrevision
              description: The git revision
              default: staging
            - name: gitrepositoryurl
              description: The git repository url
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: tekton-statuspage-
                labels:
                  tekton.dev/pipeline: statuspage
                annotations:
                  argocd.argoproj.io/compare-options: IgnoreExtraneous
                  argocd.argoproj.io/sync-options: Prune=false
              spec:
                serviceAccountName: terraform-sa
                pipelineRef:
                  name: statuspage
                workspaces:
                  - name: shared-data-statuspage
                    volumeClaimTemplate:
                      spec:
                        storageClassName: longhorn
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tb-gitea-statuspage
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
