gaps:
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "tunnel"
      hosts:
        - host: &host gaps.dex136.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gaps-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      existingClaim: pvc-gaps-data
  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chown -R 568:568 /usr/data"]
      volumeMounts:
      - name: data
        mountPath: /usr/data
      securityContext:
        runAsUser: 0
