overseerr:
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "database-check"
        nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/overseerr/dark.css"></head>';
            sub_filter_once on;
      hosts:
        - host: &host overseerr.dex136.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: overseerr-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      existingClaim: pvc-overseerr-config
  resources:
    requests:
      cpu: 1m
      memory: 200Mi
