ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      loadBalancerIP: "192.168.1.222"
  tcp:
    22: gitea/gitea-ssh:22
