.POSIX:

default: bootstrap

.PHONY: bootstrap
bootstrap:
	make -C bootstrap

.PHONY: namespace
bootstrap:
	make -C bootstrap namespace

.PHONY: argocd
bootstrap:
	make -C bootstrap argocd

.PHONY: root
bootstrap:
	make -C bootstrap root
