apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: homelab
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: http://gitea-http.gitea:3000/ops/homelab
        - name: revision
          value: main
        - name: subdirectory
          value: git
    - name: lint
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      taskRef:
        name: lint
    - name: external
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      taskRef:
        name: terraform-external
    - name: secrets
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      taskRef:
        name: terraform-secrets
