- name: Bootstrap external secrets
  hosts: localhost
  vars_prompt:
    - name: DISCORD_WEBHOOK
      prompt: Enter Discord webhook url
    - name: UN_SONARR_0_API_KEY
      prompt: Enter sonarr API key
    - name: UN_RADARR_0_API_KEY
      prompt: Enter radarr API key
    - name: UN_LIDARR_0_API_KEY
      prompt: Enter lidarr API key
    - name: gitea_password
      prompt: Enter gitea admin password
    - name: cloudflare_key
      prompt: Enter cloudflare API key (Zone 1)
    - name: cloudflare_zone_id
      prompt: Enter cloudflare Zone ID (Zone 1)
    - name: cloudflare_record_id
      prompt: Enter cloudflare record id (Zone 1)
    - name: cloudflare_key2
      prompt: Enter cloudflare API key (Zone 2)
    - name: cloudflare_zone_id2
      prompt: Enter cloudflare Zone ID (Zone 2)
    - name: cloudflare_record_id2
      prompt: Enter cloudflare record id (Zone 2)
    - name: renovate_gh_token
      prompt: Enter github personal access token
    - name: renovate_token
      prompt: Enter gitea personal access token
    - name: PODCAST_0
      prompt: Enter podcast RSS URL (0)
    - name: FILEPATH_0
      prompt: Enter podcast save path (0)
    - name: PODCAST_1
      prompt: Enter podcast RSS URL (1)
    - name: FILEPATH_1
      prompt: Enter podcast save path (1)
    - name: PODCAST_2
      prompt: Enter podcast RSS URL (2)
    - name: FILEPATH_2
      prompt: Enter podcast save path (2)
  tasks:
    - name: Render environment file
      template:
        src: ./terraform.tfvars.j2
        dest: ./terraform.tfvars
