jellyfin:
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "jellyfish"
      hosts:
        - host: &host jellyfin.dex136.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      existingClaim: pvc-jellyfin-config
    media:
      enabled: true
      mountPath: /media
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.8
          path: /volume1/MediaLibrary
  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chown -R 568:568 /config"]
      volumeMounts:
      - name: config
        mountPath: /config
      securityContext:
        runAsUser: 0
